### PR TITLE
test

### PR DESCRIPTION
**Pull request by yanbi**

### CODE REVIEW

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/19/
<h3>All tests succeeded!</h3>

The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/19/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbiTest** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/20/
<h3>All tests succeeded!</h3>

The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/20/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/21/
<h3>All tests succeeded!</h3>

The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/21/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/24/
<h3>All tests succeeded!</h3>

The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/24/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Pull request merged**
