### PR TITLE
add conflict on PR

### PR DESCRIPTION
**Pull request by yanbi**

### CODE REVIEW

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_javaDemo/33/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_javaDemo/33/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_javaDemo/34/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_javaDemo/34/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/1/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/1/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/2/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/2/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_javaDemo/35/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_javaDemo/35/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/3/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/3/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/4/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/4/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/5/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/5/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/6/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/6/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbiTest** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/7/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/7/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbiTest** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/8/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/8/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbiTest** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/9/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/9/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbiTest** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/10/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/10/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbiTest** [comment]
Run JUnit

**Comment by yanbiTest** [comment]
Run JUnit

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/14/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/14/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/15/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/15/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Comment by yanbi** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://danik22.fzi.de:8080//job/Pull_request_listner_Conflict_javaDemo/16/
<h3>Some tests failed!</h3>

JUnit Tests:
The Console Log: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/16/console

The detailed test reports can be found at: http://danik22.fzi.de:8080/job/Pull_request_listner_Conflict_javaDemo/ws/junit/index.html

**Pull request closed without merging**
